# Generated by Django 5.2.7 on 2025-10-27 08:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('AVL', 'Available'), ('DSP', 'Dispatched'), ('OSC', 'On Scene'), ('OOS', 'Out of Service')], default='AVL', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('congestion_level', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HI', 'High')], max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(help_text="e.g., 'Main St & 2nd Ave'", max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('incident_type', models.CharField(choices=[('ACC', 'Accident'), ('CON', 'Congestion'), ('WRK', 'Road Work'), ('OTH', 'Other')], max_length=3)),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('assigned_unit', models.ForeignKey(blank=True, limit_choices_to={'status': 'AVL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.responseunit')),
            ],
        ),
    ]
