# Generated by Django 5.2.7 on 2025-10-27 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='description',
        ),
        migrations.AddField(
            model_name='incident',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responseunit',
            name='unit_type',
            field=models.CharField(choices=[('Police', 'Police'), ('Ambulance', 'Ambulance'), ('Fire', 'Fire'), ('Tow', 'Tow Truck')], default='Police', max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='assigned_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.responseunit'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('ACCIDENT', 'Accident'), ('CONGESTION', 'Heavy Congestion'), ('ROAD_WORK', 'Road Work'), ('HAZARD', 'Road Hazard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='responseunit',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Dispatched', 'Dispatched'), ('On_Scene', 'On Scene'), ('Unavailable', 'Unavailable')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='trafficreport',
            name='congestion_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20),
        ),
    ]
